CREATE TABLE PRODUCT
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME             NVARCHAR(255) NOT NULL,
    PRICE               BIGINT NOT NULL,
    WEIGHT              INT    NOT NULL,
    QUANTITY            INT    NOT NULL,
    `DESCRIPTION`       TEXT   NOT NULL,
    QUANTITY_SOLD       INT,
    IMAGE_URL           TEXT,
    SUB_CATEGORY_ID BIGINT,
    FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES SUB_CATEGORY (ID),
    IS_DELETE           BIT DEFAULT 1,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE PRODUCT_IMAGE
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    IMAGE_URL    TEXT NOT NULL,
    PRODUCT_ID   BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    IS_DELETE    BIT DEFAULT 1,
    IS_ACTIVATED BIT DEFAULT 1
);
CREATE TABLE CATEGORY
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME NVARCHAR(255) NOT NULL,
-- IMAGE_URL
    IS_DELETE     BIT DEFAULT 1,
    IS_ACTIVATED  BIT DEFAULT 1
);
CREATE TABLE SUB_CATEGORY
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_ID BIGINT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    IS_DELETE           BIT DEFAULT 1,
    IS_ACTIVATED        BIT DEFAULT 1
);