CREATE  TABLE MEAN_OF_INDICATORS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME NVARCHAR(255) NOT NULL UNIQUE,
    MEAN TEXT,
    IS_DELETED     BIT DEFAULT 0,
    IS_ACTIVATED  BIT DEFAULT 1
);

CREATE TABLE LIFE_PATH_NUMBER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    OVERVIEW NVARCHAR(255),
    NATURE TEXT,
    HOBBIES TEXT,
    CAREER_DEVELOPMENT_ORIENTATION TEXT,
    JOB TEXT,
    FINANCE TEXT,
    LOVE TEXT,
    HEALTH TEXT,
    KARMA TEXT,
    SELF_SUGGESTION TEXT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);

CREATE TABLE DAY_OF_BIRTH_NUMBER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE ATTITUDE_NUMBER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE SOUL_NUMBER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE PERSONALITY_NUMBER(
    ID INT   PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE MISSION_NUMBER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE MIDDLE_AGE_NUMBER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE LIFE_PHASE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    YOUNG TEXT,
    MIDDLE_AGE TEXT,
    OLD TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE KARMIC_DEBT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE PERSONAL_YEAR(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE PERSONAL_MONTH(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE PINNACLE_OF_LIFE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE FEELING_INSIDE_NUMBER(
     ID INT  PRIMARY KEY AUTO_INCREMENT,
     INDICATORS INT,
     DESCRIPTION TEXT,
     IS_DELETED           BIT DEFAULT 0,
     IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE DEFECT_NUMBER_OF_NAME_CHART(
    ID INT  PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE CHALLENGE_NUMBER(
    ID INT  PRIMARY KEY AUTO_INCREMENT,
    INDICATORS INT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE NUMBERS_IN_CHART(
     ID INT  PRIMARY KEY AUTO_INCREMENT,
     INDICATORS TEXT,
     DESCRIPTION TEXT,
     IS_DELETED           BIT DEFAULT 0,
     IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE BALANCE_CHART(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INDICATORS TEXT,
    DESCRIPTION TEXT,
    IS_DELETED           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE NUMEROLORY_REPORT(
      ID BIGINT PRIMARY KEY AUTO_INCREMENT,
      FULL_NAME NVARCHAR(255) NOT NULL,
      DAY_OF_BIRTH INT NOT NULL ,
      MONTH_OF_BIRTH INT NOT NULL,
      YEAR_OF_BIRTH INT NOT NULL,
      IS_DELETED           BIT DEFAULT 0,
      IS_ACTIVATED        BIT DEFAULT 1,
      USER_ID      BIGINT,
      FOREIGN KEY (USER_ID) REFERENCES USER (ID),

      LIFE_PATH_NUMBER_ID INT,
      FOREIGN KEY (LIFE_PATH_NUMBER_ID) REFERENCES LIFE_PATH_NUMBER (ID),

      DAY_OF_BIRTH_NUMBER_ID INT,
      FOREIGN KEY (DAY_OF_BIRTH_NUMBER_ID) REFERENCES DAY_OF_BIRTH_NUMBER (ID),

      ATTITUDE_NUMBER_ID INT,
      FOREIGN KEY (ATTITUDE_NUMBER_ID) REFERENCES ATTITUDE_NUMBER (ID),

      SOUL_NUMBER_ID INT,
      FOREIGN KEY (SOUL_NUMBER_ID) REFERENCES SOUL_NUMBER (ID),

      PERSONALITY_NUMBER_ID INT,
      FOREIGN KEY (PERSONALITY_NUMBER_ID) REFERENCES PERSONALITY_NUMBER (ID),

      MISSION_NUMBER_ID INT,
      FOREIGN KEY (MISSION_NUMBER_ID) REFERENCES MISSION_NUMBER (ID),

      MIDDLE_AGE_NUMBER_ID INT,
      FOREIGN KEY (MIDDLE_AGE_NUMBER_ID) REFERENCES MIDDLE_AGE_NUMBER (ID),

      LIFE_PHASE_ID INT,
      FOREIGN KEY (LIFE_PHASE_ID) REFERENCES LIFE_PHASE (ID),

      KARMIC_DEBT_ID INT,
      FOREIGN KEY (KARMIC_DEBT_ID) REFERENCES KARMIC_DEBT (ID),

      PERSONAL_YEAR_ID INT,
      FOREIGN KEY (PERSONAL_YEAR_ID) REFERENCES PERSONAL_YEAR (ID),

      PINNACLE_OF_LIFE_ID INT,
      FOREIGN KEY (PINNACLE_OF_LIFE_ID) REFERENCES PINNACLE_OF_LIFE (ID),

      FEELING_INSIDE_NUMBER_ID INT,
      FOREIGN KEY (FEELING_INSIDE_NUMBER_ID) REFERENCES FEELING_INSIDE_NUMBER (ID),

      DEFECT_NUMBER_OF_NAME_CHART_ID INT,
      FOREIGN KEY (DEFECT_NUMBER_OF_NAME_CHART_ID) REFERENCES DEFECT_NUMBER_OF_NAME_CHART(ID),

      CHALLENGE_NUMBER_ID INT,
      FOREIGN KEY (CHALLENGE_NUMBER_ID) REFERENCES CHALLENGE_NUMBER (ID),

      NUMBERS_IN_CHART_ID INT,
      FOREIGN KEY (NUMBERS_IN_CHART_ID) REFERENCES NUMBERS_IN_CHART (ID),

      BALANCE_CHART_ID INT,
      FOREIGN KEY (BALANCE_CHART_ID) REFERENCES BALANCE_CHART (ID)
);