CREATE TABLE HISTORY_PAYMENT
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_INFO          VARCHAR(255),
    STATUS              BIT,
    PAYMENT_TIME        VARCHAR(55),
    TRANSACTION_ID      VARCHAR(255),
    TOTAL_PRICE         INT DEFAULT 0,
    USER_ID             BIGINT,
    IS_DELETE           BIT DEFAULT 1,
    IS_ACTIVATED        BIT DEFAULT 1,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

