ALTER TABLE NUMEROLOGY_REPORT
DROP COLUMN PINNACLE_OF_LIFE;

ALTER TABLE NUMEROLOGY_REPORT
DROP COLUMN NUMBERS_IN_CHART;

ALTER TABLE NUMEROLOGY_REPORT
DROP COLUMN DEFECT_NUMBER_OF_NAME_CHART;

ALTER TABLE NUMEROLOGY_REPORT
DROP COLUMN FEELING_INSIDE_NUMBER;

ALTER TABLE NUMEROLOGY_REPORT
DROP COLUMN KARMIC_DEBT;

ALTER TABLE NUMEROLOGY_REPORT
DROP COLUMN PERSONALITY_NUMBER;

ALTER TABLE NUMEROLOGY_REPORT
ADD COLUMN NICKNAME NVARCHAR(100);