CREATE TABLE HISTORY_PAYMENT
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    PAYMENT_ID          VARCHAR(55) UNIQUE,
    ORDER_INFO          VARCHAR(255),
    STATUS              BIT DEFAULT 0,
    PAYMENT_TIME        VARCHAR(55),
    TRANSACTION_ID      VARCHAR(255),
    TOTAL_PRICE         VARCHAR(55),
    USER_ID             BIGINT,
    IS_DELETED          BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

