CREATE TABLE `ADDRESS`
(
    ID                     BIGINT PRIMARY KEY AUTO_INCREMENT,
    CONSIGNEE_NAME         NVARCHAR(50) NOT NULL,
    COMPANY_NAME           NVARCHAR(50),
    PHONE_NUMBER           VARCHAR(11),
    DELIVERY_ADDRESS       NVARCHAR(255) NOT NULL,
    ADDITIONAL_INFORMATION TEXT,
    USER_DETAIL_ID BIGINT,
    FOREIGN KEY (USER_DETAIL_ID) REFERENCES USER_DETAIL (ID)
);
CREATE TABLE `ORDER`
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID      BIGINT,
    ORDER_DATE   DATE,
    TOTAL_AMOUNT BIGINT,
    STATUS       NVARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE ORDER_DETAIL
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    QUANTITY    INT,
    TOTAL_PRICE BIGINT,
    ORDER_ID    BIGINT,
    PRODUCT_ID  BIGINT,
    FOREIGN KEY (ORDER_ID) REFERENCES `ORDER` (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
CREATE TABLE CART
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT_TOTAL BIGINT,
    USER_ID      BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE CART_LINE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    CART_ID     BIGINT,
    PRODUCT_ID  BIGINT,
    QUANTITY    INT,
    TOTAL_PRICE BIGINT,
    FOREIGN KEY (CART_ID) REFERENCES `CART` (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

