CREATE  TABLE PINNACLE_OF_LIFE(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PINNACLE_OF_LIFE_NUMBER INT NOT NULL,
    AGE INT NOT NULL,
    NUMEROLOGY_REPORT_ID BIGINT,
    FOREIGN KEY (NUMEROLOGY_REPORT_ID) REFERENCES NUMEROLOGY_REPORT (ID)
);

ALTER TABLE NUMEROLOGY_REPORT
    CHANGE BALANCE_CHART BALANCE_NUMBER INT;