CREATE TABLE CATEGORY
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME NVARCHAR(255) NOT NULL,
    IS_DELETE     BIT DEFAULT 0,
    IS_ACTIVATED  BIT DEFAULT 1
);
CREATE TABLE SUB_CATEGORY
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME NVARCHAR(50) NOT NULL,
    CATEGORY_ID BIGINT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    IS_DELETE           BIT DEFAULT 0,
    IS_ACTIVATED        BIT DEFAULT 1
);
CREATE TABLE PRODUCT
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME    NVARCHAR(255) NOT NULL,
    PRICE           BIGINT NOT NULL,
    QUANTITY_SOLD   INT DEFAULT 0,
    WEIGHT          INT,
    QUANTITY        INT,
    `DESCRIPTION`   TEXT,
    PRODUCER        NVARCHAR(50),
    AUTHOR          NVARCHAR(50),
    INCLUDE         NVARCHAR(255),
    IMAGE_URL       TEXT,
    SUB_CATEGORY_ID BIGINT,
    FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES SUB_CATEGORY (ID),
    IS_DELETE       BIT DEFAULT 0,
    IS_ACTIVATED    BIT DEFAULT 1
);
CREATE TABLE PRODUCT_IMAGE
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    IMAGE_URL    TEXT NOT NULL,
    PRODUCT_ID   BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    IS_DELETE    BIT DEFAULT 0,
    IS_ACTIVATED BIT DEFAULT 1
);
