CREATE TABLE `ORDERS`
(
    ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID           BIGINT,
    ORDER_DATE        DATE,
    TOTAL_AMOUNT      BIGINT,
    EXPECTED_DELIVERY DATE,
    STATUS            NVARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE `ADDRESS`
(
    ID                     BIGINT PRIMARY KEY AUTO_INCREMENT,
    CONSIGNEE_NAME         NVARCHAR(50),
    FULL_NAME              NVARCHAR(255),
    PHONE_NUMBER           VARCHAR(11),
    CITY                   NVARCHAR(50),
    DELIVERY_ADDRESS       NVARCHAR(255),
    DELIVERY_CHARGES       BIGINT,
    ADDITIONAL_INFORMATION TEXT,
    ORDER_ID               BIGINT UNIQUE,
    FOREIGN KEY (ORDER_ID) REFERENCES `ORDERS` (ID)
);

CREATE TABLE ORDER_DETAIL
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    QUANTITY    INT,
    TOTAL_PRICE BIGINT,
    ORDER_ID    BIGINT,
    PRODUCT_ID  BIGINT,
    FOREIGN KEY (ORDER_ID) REFERENCES `ORDERS` (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE CART
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    TOTAL_AMOUNT BIGINT,
    USER_ID      BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE CART_LINE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    CART_ID     BIGINT,
    PRODUCT_ID  BIGINT,
    QUANTITY    INT,
    TOTAL_PRICE BIGINT,
    FOREIGN KEY (CART_ID) REFERENCES `CART` (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);