CREATE TABLE `ORDER`
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID          BIGINT,
    ORDER_DATE       DATE,
    TOTAL_AMOUNT     BIGINT,
    DELIVERY_ADDRESS NVARCHAR(255),
    STATUS           NVARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE ORDER_DETAIL
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID    BIGINT,
    PRODUCT_ID  BIGINT,
    QUANTITY    INT,
    TOTAL_PRICE BIGINT,
    FOREIGN KEY (ORDER_ID) REFERENCES `ORDER` (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

