INSERT INTO `aurora_shop`.`category` (`NAME`) VALUES ( 'Vòng Tay Phong Thủy');
INSERT INTO `aurora_shop`.`category` (`NAME`) VALUES ('Ngọc Bích Nephrite' );
INSERT INTO `aurora_shop`.`category` (`NAME`) VALUES ('Nhẫn Phong Thủy' );
INSERT INTO `aurora_shop`.`category` (`NAME`) VALUES ('Dây Chuyền Phong Thủy' );
INSERT INTO `aurora_shop`.`category` (`NAME`) VALUES ('Vật Phẩm Phong Thủy');
INSERT INTO `aurora_shop`.`category` (`NAME`) VALUES ('Hoa Tai Phong Thủy' );
INSERT INTO `aurora_shop`.`category` (`NAME`) VALUES ('Tarot' );

INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Vòng tay đá Mặt Trăng', '1');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Vòng Tay Tết Dây Dù', '1');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Vòng tay đá Thạch Anh', '1');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Vòng tay mix Charm bạc', '1');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Mặt đá Nephrite', '2');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Vòng tay Nephrite', '2');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Nhẫn Tỳ Hưu', '3');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Nhẫn Hồ Ly', '3');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Nhẫn Ngọc Trai', '3');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Mặt dây hồ ly', '4');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Mặt dây phật Di Lặc', '4');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Tượng phật Di Lặc', '5');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Cây Tài Lộc', '5');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Tỳ hưu', '5');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Bài TAROT', '7');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Bài ORACLE', '7');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Bài LENORMAND', '7');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Sách Tham Khảo', '7');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Con Lắc', '7');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Đá Runes', '7');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Đá Thanh Tẩy', '7');
INSERT INTO `aurora_shop`.`sub_category` (`NAME`, `CATEGORY_ID`) VALUES ('Khăn Trải', '7');