INSERT INTO `aurora_shop`.`category` (`name`)
VALUES ('Vòng Tay Phong Thủy'),
       ('Ngọc Bích Nephrite'),
       ('Nhẫn Phong Thủy'),
       ('Dây Chuyền Phong Thủy'),
       ('Vật Phẩm Phong Thủy'),
       ('Hoa Tai Phong Thủy'),
       ('Tarot');

INSERT INTO `aurora_shop`.`sub_category` (`name`, `category_id`)
VALUES ('Vòng tay đá Mặt Trăng', '1'),
       ('Vòng Tay Tết Dây Dù', '1'),
       ('Vòng tay đá Thạch Anh', '1'),
       ('Vòng tay mix Charm bạc', '1'),
       ('Mặt đá Nephrite', '2'),
       ('Vòng tay Nephrite', '2'),
       ('Nhẫn Tỳ Hưu', '3'),
       ('Nhẫn Hồ Ly', '3'),
       ('Nhẫn Ngọc Trai', '3'),
       ('Mặt dây hồ ly', '4'),
       ('Mặt dây phật Di Lặc', '4'),
       ('Tượng phật Di Lặc', '5'),
       ('Cây Tài Lộc', '5'),
       ('Tỳ hưu', '5'),
       ('Bài TAROT', '7'),
       ('Bài ORACLE', '7'),
       ('Bài LENORMAND', '7'),
       ('Sách Tham Khảo', '7'),
       ('Con Lắc', '7'),
       ('Đá Runes', '7'),
       ('Đá Thanh Tẩy', '7'),
       ('Khăn Trải', '7');